<?php
use Emmet\Emmet;
require_once 'Emmet.php';

$itags = array(
	'audio' => 'source',
	'colgroup' => 'col',
	'datalist' => 'option',
	'details' => 'summary',
	'dl' => 'dt',
	'em' => 'span',
	'fieldset' => 'legend',
	'figure' => 'figcaption',
	'frameset' => 'frame',
	'html' => 'body',
	'input' => 'input',
	'label' => 'input',
	'map' => 'area',
	'menu' => 'menuitem',
	'menuitem' => 'menuitem',
	'ul' => 'li',
	'ol' => 'li',
	'picture' => 'img',
	'object' => 'param',
	'optgroup' => 'option',
	'select' => 'option',
	'table' => 'tr',
	'tbody' => 'tr',
	'thead' => 'tr',
	'tfoot' => 'tr',
	'tr' => 'td',
	'video' => 'source'
);
$tabbr = array(
	'!' => '!DOCTYPE html',
	'ab' => 'abbr',
	'acronym' => 'acr',
	'adr' => 'address',
	'ar' => 'area',
	'arti' => 'article',
	'asd' => 'aside',
	'bq' => 'blockquote',
	'btn' => 'button',
	'colg' => 'colgroup',
	'cap' => 'caption',
	'cmd' => 'command',
	'cv' => 'canvas',
	'dat' => 'data',
	'datg' => 'datagrid', 'datag' => 'datagrid',
	'datl' => 'datalist', 'datal' => 'datalist',
	'det' => 'details',
	'dlg' => 'dlg',
	'emb' => 'embed',
	'fg' => 'figure', 'fig' => 'figure',
	'fgc' => 'figcaption', 'figc' => 'figcaption',
	'fm' => 'form',
	'fst' => 'fieldset', 'fset' => 'fieldset',
	'frs' => 'frameset',
	'ftr' => 'footer',
	'hd' => 'head',
	'hdr' => 'header',
	'hg' => 'hgroup',
	'htm' => 'html',
	'ifr' => 'iframe',
	'inp' => 'input',
	'kg' => 'keygen',
	'lab' => 'label',
	'leg' => 'legend',
	'mi' => 'menuitem',
	'mk' => 'mark',
	'mn' => 'main',
	'nos' => 'noscript',
	'obj' => 'object',
	'opt' => 'option',
	'optg' => 'optgroup',
	'out' => 'output',
	'pic' => 'picture',
	'pr' => 'pre',
	'prog' => 'progress',
	'scr' => 'script',
	'sect' => 'section',
	'sel' => 'select',
	'sm' => 'samp',
	'summ' => 'summary',
	'sp' => 'span',
	'src' => 'source',
	'str' => 'strong',
	'sty' => 'style',
	'tab' => 'table',
	'tbd' => 'tbody',
	'tem' => 'template',
	'tft' => 'tfoot',
	'thd' => 'thead',
	'tpl' => 'template',
	'tra' => 'track',
	'trk' => 'track',
	'txa' => 'textarea',
	'vid' => 'video',
	'wb' => 'wbr'
);
$aabbr = array(
	"a" => "alt",
	"ak" => "accesskey",
	"ce" => "contenteditable",
	"cm" => "contextmenu",
	"d" => "dir",
	"dr" => "draggable",
	"dz" => "dropzone",
	"dz" => "dropzone",
	"n" => "name",
	"h" => "height",
	"hid" => "hidden",
	"l" => "lang",
	"s" => "style",
	"sc" => "spellcheck",
	"t" => "title",
	"ti" => "tabindex",
	"ty" => "type",
	"v" => "value",
	"w" => "width"
);
$eabbr = array(
	"css" => ' rel="stylesheet"',
	"print" => ' rel="stylesheet" media="print"',
	"favicon" => ' rel="shortcut icon" type="image/x-icon" href="favicon.ico"',
	"touch" => ' rel="apple-touch-icon"',
	"rss" => ' rel="alternate" type="application/rss+xml" title="RSS"',
	"atom" => ' rel="alternate" type="application/atom+xml" title="Atom"',
	"import" => ' rel="import"',
	"im" => ' rel="import"',
	"utf" => ' http-equiv="Content-Type" content="text/html;charset=UTF-8"',
	"win" => ' http-equiv="Content-Type" content="text/html;charset=windows-1251"',
	"vp" => ' name="viewport"',
	"d" => ' disabled="disabled"',
	"hidden" => ' type="hidden"',
	"h" => ' type="hidden"',
	"text" => ' type="text"',
	"t" => ' type="text"',
	"search" => ' type="search"',
	"email" => ' type="email"',
	"url" => ' type="url"',
	"password, input:p" => ' type="password"',
	"datetime" => ' type="datetime"',
	"date" => ' type="date"',
	"datetime-local" => ' type="datetime-local"',
	"month" => ' type="month"',
	"week" => ' type="week"',
	"time" => ' type="time"',
	"tel" => ' type="tel"',
	"number" => ' type="number"',
	"color" => ' type="color"',
	"checkbox" => ' type="checkbox"',
	"c" => ' type="checkbox"',
	"radio" => ' type="radio"',
	"r" => ' type="radio"',
	"range" => ' type="range"',
	"file" => ' type="file"',
	"f:" => ' type="file"',
	"submit" => ' type="submit"',
	"s" => ' type="submit"',
	"image, input:i" => ' type="image"',
	"button" => ' type="button"',
	"b" => ' type="button"',
	"reset" => ' type="reset"'
);

$emmet = new Emmet($tabbr, $aabbr, $itags, $eabbr);